services:
  - type: web
    name: metabase
    env: docker
    region: frankfurt
    repo: https://github.com/pluz-care/metabase.git # optional
    plan: standard # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: metabase_production
          property: connectionString
databases:
  - name: metabase_production
    databaseName: metabasedb
    region: frankfurt
    ipAllowList: [] # only allow internal connections
